list: $/diveramkt/manual/models/videos/columns.yaml
modelClass: Diveramkt\Manual\Models\Videos
title: Videos
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/manual/videos/update/:id'
