list: $/diveramkt/manual/models/manual/columns.yaml
modelClass: Diveramkt\Manual\Models\Manual
title: Manual
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/manual/manual/update/:id'
